services:
  #  mongodb:
  #    image: 'mongo:latest'
  #    environment:
  #      - 'MONGO_INITDB_DATABASE=mydatabase'
  #      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
  #      - 'MONGO_INITDB_ROOT_USERNAME=root'
  #    ports:
  #      - '27017'
  postgres:
    image: 'postgres:14'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5431:5432'
#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'
